platform :ios, '8.0'

inhibit_all_warnings!

pod 'AFNetworking'
pod 'CDYObjectModel', :git => 'https://github.com/coodly/CDYObjectModel.git'
pod 'JCSFoundation/UserInput', :git => 'https://github.com/jaanussiim/JCSFoundation.git'
pod 'JCSFoundation/CoreData', :git => 'https://github.com/jaanussiim/JCSFoundation.git'
pod 'JCSFoundation/PopupViews', :git => 'https://github.com/jaanussiim/JCSFoundation.git'
#pod 'JCSFoundation/UserInput', :path => '../JCSFoundation'
#pod 'JCSFoundation/CoreData', :path => '../JCSFoundation'
#pod 'JCSFoundation/PopupViews', :path => '../JCSFoundation'
pod 'CDYFoundation', :git => 'https://github.com/coodly/CDYFoundation.git'
pod 'Fabric'
pod 'Crashlytics'
pod 'MRProgress'
pod 'RMStore/Core', '0.6'
pod 'RMStore/KeychainPersistence', '0.6'
pod 'RMStore/AppReceiptVerificator', '0.6'
pod 'NSString-UrlEncode'
pod 'Google-AdMob-Ads-SDK', '6.8.0'
pod 'CDYAdLoader', :git => 'https://github.com/coodly/CDYAdLoader.git'
pod 'Lockbox'
pod '1PasswordExtension', '~> 1.5'